// Default product catalog data used across the site
// Admin overrides are stored in localStorage under "shoesx_products"
window.SHOESX_DEFAULT_PRODUCTS = [
  {
    id: 'aeroflex-runner',
    name: 'AeroFlex Runner',
    price: '$149',
    priceNum: 149,
    category: 'Running',
    rating: 4.8,
    sizes: 'UK 6-11',
    colors: ['Graphite', 'Arctic Blue'],
    description: 'Lightweight knit runner with carbon-infused midsole. Perfect for daily runs and long-distance training. Features breathable mesh upper and responsive cushioning.',
    shortDescription: 'Maximum cushioning and dual Air Zoom units deliver an ultra-soft ride.',
    image: 'https://images.unsplash.com/photo-1528701800489-20be9c1e74bb?auto=format&fit=crop&w=900&q=60',
    cardImage: 'assets/NIKE+VOMERO+PREMIUM.avif',
    fitScore: 94,
    badge: 'New drop',
    logistics: ['2-day dispatch', 'Low return risk']
  },
  {
    id: 'pulse-knit-sneaker',
    name: 'Pulse Knit Sneaker',
    price: '$129',
    priceNum: 129,
    category: 'Casual',
    rating: 4.7,
    sizes: 'UK 5-10',
    colors: ['Black', 'Sand'],
    description: 'Breathable knit upper with adaptive foam cushioning. Ideal for everyday wear with maximum comfort and style.',
    shortDescription: 'Classic Samba-inspired knit with modern comfort.',
    image: 'https://images.unsplash.com/photo-1514986888952-8cd320577b68?auto=format&fit=crop&w=900&q=60',
    cardImage: 'assets/IMG_6951.webp',
    fitScore: 90,
    badge: 'Popular',
    logistics: ['Flexible knit', 'Carbon neutral ship']
  },
  {
    id: 'vertex-trail-pro',
    name: 'Vertex Trail Pro',
    price: '$169',
    priceNum: 169,
    category: 'Trail',
    rating: 4.9,
    sizes: 'UK 7-12',
    colors: ['Olive', 'Burnt Orange'],
    description: 'Aggressive outsole with waterproof mesh upper. Built for rugged terrain and challenging trails.',
    shortDescription: 'Aggressive outsole with waterproof mesh upper.',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=60',
    cardImage: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=60',
    fitScore: 96,
    badge: 'Trail tested',
    logistics: ['Waterproof mesh', 'Grip rated 5/5']
  },
  {
    id: 'forma-luxe-oxford',
    name: 'Forma Luxe Oxford',
    price: '$189',
    priceNum: 189,
    category: 'Formal',
    rating: 4.6,
    sizes: 'UK 6-12',
    colors: ['Chestnut', 'Midnight'],
    description: 'Hand-finished leather upper with memory foam insole. Elegant design for professional and formal occasions.',
    shortDescription: 'Hand-finished leather upper with memory foam insole.',
    image: 'https://images.unsplash.com/photo-1475180098004-ca77a66827be?auto=format&fit=crop&w=900&q=60',
    cardImage: 'assets/png-clipart-men-shoes-men-shoes.png',
    fitScore: 88,
    badge: 'Premium leather',
    logistics: ['Memory foam footbed', 'Free polish kit']
  },
  {
    id: 'halo-court',
    name: 'Halo Court',
    price: '$139',
    priceNum: 139,
    category: 'Athletic',
    rating: 4.5,
    sizes: 'UK 6-11',
    colors: ['White', 'Navy'],
    description: 'Court-ready leather sneaker with cushioned heel pod. Perfect for indoor sports and casual wear.',
    shortDescription: 'Court-ready leather sneaker with cushioned heel pod.',
    image: 'https://images.unsplash.com/photo-1549298916-5a8b0c6908d1?auto=format&fit=crop&w=900&q=60',
    cardImage: 'https://images.unsplash.com/photo-1549298916-5a8b0c6908d1?auto=format&fit=crop&w=900&q=60',
    fitScore: 91,
    badge: 'Court favorite',
    logistics: ['Heel stability', 'Indoor grip']
  },
  {
    id: 'nimbus-glide',
    name: 'Nimbus Glide',
    price: '$159',
    priceNum: 159,
    category: 'Running',
    rating: 4.8,
    sizes: 'UK 6-12',
    colors: ['Silver', 'Neon Lime'],
    description: 'Energy-return midsole with breathable engineered mesh. Advanced cushioning technology for maximum performance.',
    shortDescription: 'Energy-return midsole with breathable engineered mesh.',
    image: 'https://images.unsplash.com/photo-1549298916-12346510946f?auto=format&fit=crop&w=900&q=60',
    cardImage: 'https://images.unsplash.com/photo-1549298916-12346510946f?auto=format&fit=crop&w=900&q=60',
    fitScore: 93,
    badge: 'Runner pick',
    logistics: ['Energy return', 'Breathable mesh']
  }
];
